try {
  //  Where Exception can happen. 
}
catch(Exception e) {
  //  Handle errors here.
}
